const data = {
  "hi":"Hi! I can help with answers or create flowcharts. Just ask!",
  "what is the purpose of this application": "The application enables interactive semantic segmentation of images from WMS services using on-device GPUs/NPUs. It is designed to assist users in digitizing geospatial features efficiently for remote sensing applications.",
  "Who is this application designed for": "It is designed for WebGIS application developers and end-users who need geospatial data for analysis, such as planners, researchers, and GIS professionals.",
  "What features does this application offer": "Integration with OGC-compliant WMS services. Interactive semantic segmentation using on-device computational power. Export of user-selected features in geospatial formats like GeoJSON or KML.",
  "How does this application utilize on-device GPUs/NPUs": "The application uses GPU/NPU acceleration for real-time image processing and semantic segmentation, enhancing responsiveness while reducing reliance on server-side computation.",
  "What file formats can be exported from the application": "User-selected features can be exported in GeoJSON or KML formats for compatibility with other GIS tools.",
  "What is WMS, and why is it used in this application": "WMS (Web Map Service) is an OGC standard for serving georeferenced map images over the internet. It is used in this application to provide the base imagery for semantic segmentation.",
  "What are the hardware requirements for running this application": "The application requires modern devices equipped with GPUs or NPUs, commonly available in smartphones, tablets, and desktop computers.",
  "Can this tool handle large datasets": "Yes, but performance depends on the device’s hardware capabilities. GPU/NPU acceleration ensures that most devices can handle reasonably large datasets efficiently.",
  "How user-friendly is this application for non-technical users": "The application is designed with a simple, intuitive interface that requires minimal training. Features like interactive selection and guided workflows make it accessible to non-technical users.",
  "How does this tool assist with on-screen digitization": "The application uses semantic segmentation to highlight features of interest, allowing users to refine selections interactively for precise digitization.",
  "Is this tool compatible with all WMS services": "The tool is compatible with OGC-compliant WMS services, ensuring interoperability with a wide range of data sources.",
  "Can this tool be integrated into existing WebGIS platforms": "Yes, the application is designed for seamless integration into WebGIS platforms, either as a plugin or standalone module.",
  "Are there any known limitations of the tool": "Current limitations include dependency on device hardware for performance and potential issues with very large or complex datasets on lower-end devices.",
  "Can I share my geospatial outputs with other tools": "Yes, the exported GeoJSON or KML files are compatible with most GIS platforms, including QGIS, ArcGIS, and Google Earth.",
  "Does this tool require an internet connection": "An internet connection is required to load WMS imagery, but segmentation and digitization work offline using on-device resources.",
  "Does this tool require an internet connection": "An internet connection is required to load WMS imagery, but segmentation and digitization work offline using on-device resources.",
    "Which type of map should I use for high-resolution imagery?": "For high-resolution imagery, you should use a Satellite or Orthophoto map layer. These are ideal for capturing detailed visual data.",
    "Which type of map is best for navigation purposes?": "For navigation, a Street Map or Topographic Map is recommended. These maps provide road networks, landmarks, and elevation details.",
    "Which map should I use for terrain analysis?": "For terrain analysis, a Topographic Map or DEM (Digital Elevation Model) is ideal. These maps include contour lines and elevation data.",
    "Can I use maps offline?": "Yes, offline maps can be used if they are pre-downloaded or cached. Ensure you have the necessary data stored on your device.",
    "What is the best map for real-time tracking?": "For real-time tracking, use a map that supports live data layers, such as a GPS-integrated Street Map or a custom WMS map with real-time feeds.",
    "Which map is recommended for agricultural analysis?": "For agricultural analysis, use a Vegetation Index Map or Satellite imagery that provides NDVI (Normalized Difference Vegetation Index) data.",
    "What map should I use for city planning?": "For city planning, use a combination of Satellite Imagery and Street Maps with cadastral data layers for detailed planning and zoning.",
    "Which type of map is suitable for disaster management?": "For disaster management, use a Crisis Map or Satellite Imagery with real-time updates and hazard overlays, such as flood zones or wildfire spreads.",
    "What type of map is ideal for historical research?": "For historical research, use Historical Map Layers or Archaeological Maps that provide insights into past geographical layouts.",
    "Which map is best for marine navigation?": "For marine navigation, use Nautical Charts that include bathymetric data and navigation aids like buoys and lighthouses.",
    "What map should I use for weather forecasting?": "For weather forecasting, use Meteorological Maps or Weather Layers with real-time radar and precipitation data.",
    "Which type of map is useful for wildlife tracking?": "For wildlife tracking, use Habitat Maps or Satellite Imagery with vegetation and terrain overlays.",
    "Can I create custom maps?": "Yes, you can create custom maps using GIS tools that allow you to layer data such as roads, boundaries, and geographic features.",
    "What map should I use for transportation analysis?": "For transportation analysis, use Traffic Maps or GIS layers with traffic density and infrastructure data.",
    "Which map is ideal for cultural heritage studies?": "For cultural heritage studies, use Archaeological Maps or Ethnographic Maps that provide details on cultural landmarks and population distributions.",
    "What map should I use for energy infrastructure planning?": "For energy infrastructure, use Utility Maps or Thematic Maps showing energy grids, pipelines, and renewable resource locations."
};

export default data;
